# Generated by Django 4.2.5 on 2023-09-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_current_price_bid_time_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
