# Generated by Django 4.2.5 on 2023-10-01 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='Watchlist',
            field=models.ManyToManyField(blank=True, related_name='auction', to=settings.AUTH_USER_MODEL),
        ),
    ]
